/**
 * One-off image pipeline for Altiere Estates.
 *
 *  1. Downloads every Unsplash photo the site references into
 *     public/images/unsplash/<id>.jpg so nothing is fetched from a
 *     third-party CDN at request time.
 *  2. Re-encodes every JPEG under public/images to a 1600px-wide,
 *     progressive, mozjpeg-compressed file (sources were ~800KB each).
 *  3. Emits lib/blur-data.ts: a tiny base64 blur placeholder per image so
 *     <Image placeholder="blur"> paints instantly before bytes arrive.
 *
 * Run:  node scripts/optimize-images.mjs
 * `sharp` is already installed transitively by Next.js.
 */
import sharp from 'sharp';
import { readdir, writeFile, mkdir, stat } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(new URL('.', import.meta.url).pathname, '..');
const PUBLIC_IMAGES = path.join(ROOT, 'public/images');
const UNSPLASH_DIR = path.join(PUBLIC_IMAGES, 'unsplash');
const MAX_WIDTH = 1600;
const JPEG_QUALITY = 76;

const UNSPLASH_IDS = [
  'photo-1497366216548-37526070297c','photo-1497366754035-f200968a6e72','photo-1497366811353-6870744d04b2',
  'photo-1512453979798-5ea266f8880c','photo-1523816572-a1a23d1a67b8','photo-1526495124232-a04e1849168c',
  'photo-1545324418-cc1a3fa10c00','photo-1600210492486-724fe5c67fb0','photo-1600566753086-00f18fb6b3ea',
  'photo-1600566753190-17f0baa2a6c3','photo-1600573472591-ee6b68d14c68','photo-1600585152915-d208bec867a1',
  'photo-1600585154526-990dced4db0d','photo-1600607687920-4e2a09cf159d','photo-1600607687939-ce8a6c25118c',
  'photo-1600607688969-a5bfcd646154','photo-1611577810610-642f8ac05c32','photo-1615747476205-991a14cd2358',
  'photo-1615747476328-41153cf6da54','photo-1627120697861-84c863582194','photo-1634007626524-f47fa37810a7',
  'photo-1654520015092-b9b4ddf2e7c7','photo-1702070114450-94d981d72233','photo-1734009775179-07f428483783',
  'photo-1779903726785-7cf25bed78f7',
];

async function download(id) {
  const out = path.join(UNSPLASH_DIR, `${id}.jpg`);
  if (existsSync(out)) return out;
  const url = `https://images.unsplash.com/${id}?fm=jpg&fit=max&w=${MAX_WIDTH}&q=90`;
  const res = await fetch(url, { headers: { 'user-agent': 'Mozilla/5.0' } });
  if (!res.ok) throw new Error(`${id}: HTTP ${res.status}`);
  await writeFile(out, Buffer.from(await res.arrayBuffer()));
  return out;
}

async function compress(file) {
  const before = (await stat(file)).size;
  const buf = await sharp(file)
    .rotate()
    .resize({ width: MAX_WIDTH, withoutEnlargement: true })
    .jpeg({ quality: JPEG_QUALITY, mozjpeg: true, progressive: true, chromaSubsampling: '4:2:0' })
    .toBuffer();
  await writeFile(file, buf);
  return { before, after: buf.length };
}

async function blur(file) {
  const buf = await sharp(file).resize(12).jpeg({ quality: 40 }).toBuffer();
  return `data:image/jpeg;base64,${buf.toString('base64')}`;
}

async function* walk(dir) {
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) yield* walk(p);
    else if (/\.(jpe?g)$/i.test(e.name)) yield p;
  }
}

await mkdir(UNSPLASH_DIR, { recursive: true });
await Promise.all(UNSPLASH_IDS.map((id) => download(id).then(() => console.log('downloaded', id))));

const entries = [];
for await (const file of walk(PUBLIC_IMAGES)) {
  const { before, after } = await compress(file);
  const rel = '/' + path.relative(path.join(ROOT, 'public'), file).split(path.sep).join('/');
  entries.push([rel, await blur(file)]);
  console.log(`${rel}: ${(before / 1024).toFixed(0)}KB -> ${(after / 1024).toFixed(0)}KB`);
}
entries.sort(([a], [b]) => a.localeCompare(b));

const ts = `// Generated by scripts/optimize-images.mjs — do not edit by hand.
// Tiny base64 JPEG placeholders (12px wide) keyed by public image path.
export const BLUR_DATA: Record<string, string> = {
${entries.map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join('\n')}
};
`;
await writeFile(path.join(ROOT, 'lib/blur-data.ts'), ts);
console.log(`wrote lib/blur-data.ts (${entries.length} images)`);
